### ISSUE TITLE
Add support for Pyside2

### ISSUE THREAD

**Issue by labqui** [xxao/pero#1]
Would it be possible to insert the PySide2 backend? It is the same as Qt5, which is already supported in the current version. Thanks.

**Comment by xxao** [comment]
Why not, looks like just making the module import smarter should do the trick. The only thing is, that the PySlide2 and Qt5 seems old already. What about moving to PySlide6 and Qt6? (I am personally not using any of those so I do not know the current situation well enough.)

**Comment by xxao** [comment]
PySide2 support added into the code. _Pero_ automatically uses either PyQt5 or PySlide2, whichever is available.

**Comment by xxao** [comment]
Just added additional support for PyQt6 and PySide6. There are some compatibility issues but _Pero_ takes care of them. Still, there are some strange issues with fonts scaling and high-res monitors - Qt6 seems to handle it better.
